services:
  api:
    image: schoolapi
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: >
        Server=db;
        Database=school_db;
        User=root;
        Password=${MYSQL_ROOT_PASSWORD}

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: school_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
